# Generated by Django 6.0.4 on 2026-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaodich',
            name='da_xac_nhan',
            field=models.BooleanField(default=False, verbose_name='Thủ quỹ đã nhận tiền'),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='phuong_thuc',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK', 'Chuyển khoản / QR')], default='CASH', max_length=10, verbose_name='Phương thức'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Thủ Quỹ (Lớp trưởng)'), ('MEMBER', 'Thành Viên'), ('TESTER', 'QA/Tester')], default='MEMBER', max_length=20),
        ),
    ]
