# Generated by Django 6.0.4 on 2026-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0002_giaodich_da_xac_nhan_giaodich_phuong_thuc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quatang',
            options={},
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='hinh_anh',
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='quatang',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='quatang',
            name='mo_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='gia_xu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='loai_qua',
            field=models.CharField(choices=[('VOUCHER', 'Voucher Giảm Quỹ'), ('HIEN_VAT', 'Quà Hiện Vật'), ('DAC_QUYEN', 'Thẻ Đặc Quyền')], default='HIEN_VAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='so_luong_kho',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quatang',
            name='ten_qua',
            field=models.CharField(max_length=255),
        ),
    ]
