# Generated by Django 6.0.4 on 2026-06-27 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0003_alter_quatang_options_remove_quatang_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_invest', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='bieuquyet',
            name='loai_quy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.loaiquy', verbose_name='Quỹ sử dụng đầu tư'),
        ),
        migrations.AddField(
            model_name='bieuquyet',
            name='so_tien_dau_tu',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền đề xuất đầu tư'),
        ),
        migrations.AddField(
            model_name='bieuquyet',
            name='trang_thai_duyet',
            field=models.CharField(choices=[('PENDING', 'Chờ gom phiếu'), ('APPROVED', 'Đã thông qua'), ('REJECTED', 'Bị từ chối')], default='PENDING', max_length=20, verbose_name='Trạng thái phê duyệt'),
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='lop_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.lophoc', verbose_name='Thuộc lớp học'),
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='nam_hoc_bat_dau',
            field=models.IntegerField(default=2022, verbose_name='Năm học bắt đầu'),
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='nam_hoc_ket_thuc',
            field=models.IntegerField(default=2026, verbose_name='Năm học kết thúc'),
        ),
        migrations.AddField(
            model_name='loaiquy',
            name='trang_thai_vong_doi',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('DISBANDED', 'Đã giải tán')], default='ACTIVE', max_length=20, verbose_name='Trạng thái vòng đời'),
        ),
        migrations.CreateModel(
            name='CollectionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount_required', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.classfund')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('expired_at', models.DateTimeField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.classfund')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=10)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.investmentproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã định danh đối soát')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlyquy.collectionperiod')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.classfund')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
