# Generated by Django 6.0.4 on 2026-06-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0004_classfund_bieuquyet_loai_quy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoiDauTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ten_khoan_dau_tu', models.CharField(max_length=255, verbose_name='Tên ngân hàng / Gói đầu tư')),
                ('so_tien_goc', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số vốn đầu tư')),
                ('lai_suat_nam', models.FloatField(verbose_name='Lãi suất % / Năm')),
                ('ngay_bat_dau', models.DateTimeField(verbose_name='Ngày xuống tiền đầu tư')),
            ],
            options={
                'verbose_name': 'Khoản Đầu Tư',
                'verbose_name_plural': 'Theo Dõi Đầu Tư Gốc',
            },
        ),
    ]
