# Generated by Django 6.0.4 on 2026-07-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0005_goidautu'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanhvien',
            name='so_du',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số dư tài khoản'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='so_du_tai_khoan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số dư tài khoản riêng'),
        ),
        migrations.AddField(
            model_name='thanhvien',
            name='so_du_vi_web',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số dư tài khoản Web (VNĐ)'),
        ),
        migrations.AddField(
            model_name='tiendodongquy',
            name='da_tu_dong_khau_tru',
            field=models.BooleanField(default=False, verbose_name='Đã tự trừ tiền từ ví cá nhân'),
        ),
        migrations.AddField(
            model_name='tiendodongquy',
            name='ngay_nhac_nho_gan_nhat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hệ thống bắn nhắc nhở nợ'),
        ),
    ]
