# Generated by Django 6.0.4 on 2026-07-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0006_thanhvien_so_du_thanhvien_so_du_tai_khoan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bieuquyet',
            name='lop_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quanlyquy.lophoc', verbose_name='Dành cho lớp'),
        ),
        migrations.AlterField(
            model_name='tiendodongquy',
            name='da_tu_dong_khau_tru',
            field=models.BooleanField(default=False, verbose_name='Đã tự động trích tiền'),
        ),
        migrations.AlterField(
            model_name='tiendodongquy',
            name='ngay_nhac_nho_gan_nhat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hệ thống nhắc nợ'),
        ),
    ]
