# Generated by Django 6.0.4 on 2026-07-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0007_bieuquyet_lop_hoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bieuquyet',
            name='ngay_ket_thuc_dau_tu',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày gói đầu tư đáo hạn'),
        ),
    ]
