# Generated by Django 6.0.4 on 2026-07-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyquy', '0008_bieuquyet_ngay_ket_thuc_dau_tu'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoTaiNguyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người tạo (ID)')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người sửa (ID)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa mềm')),
                ('ten_tai_nguyen', models.CharField(max_length=150, verbose_name='Tên tài nguyên (VD: Canva Pro Nhóm 1)')),
                ('loai', models.CharField(choices=[('CHATGPT', 'Tài khoản ChatGPT Plus'), ('GEMINI', 'Tài khoản Gemini Advanced'), ('CANVA', 'Tài khoản Canva Pro (Link Đội nhóm)'), ('OTHER', 'Tài nguyên Premium khác')], default='OTHER', max_length=20, verbose_name='Phân loại tài nguyên')),
                ('tai_khoan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tài khoản / Email đăng nhập')),
                ('mat_khau', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mật khẩu / Key kích hoạt')),
                ('huong_dan', models.TextField(blank=True, null=True, verbose_name='Hướng dẫn sử dụng / Link kích hoạt nhanh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
            ],
            options={
                'verbose_name': 'Tài Nguyên Lớp',
                'verbose_name_plural': '🎁 Kho Tài Nguyên Dùng Chung',
            },
        ),
    ]
